services:
  observatory-camera:
    build: .
    container_name: observatory-camera
    user: "1000:1000"
    volumes:
      - /home/mothra/git/mothra-cams:/repo
      - /dev/bus/usb:/dev/bus/usb
      - /mnt/environment/:/mnt/environment/
      - /home/mothra:/home/mothra/
    devices:
      - /dev/bus/usb
    #privileged: true
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TZ=America/Santiago
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
